name: 'Issue Link Comment (with resolve-word)'
on:
  pull_request:
    types: [opened,synchronize]

jobs:
  issue-link:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: issue link comment
        uses: alphaleadership/add-issue-links@v2.0.4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
         
          resolve: 'true'
          
          link-style: 'comment'