name: delete opened issue
on:
  issues:
    types: [closed]
jobs:
  delete-issue:
    
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          github_token: ${{  secrets.GITHUB_TOKEN  }}
          issue_node_id: ${{ github.event.issue.node_id }}  